# Site settings
title: Nic Durish
email: n.durish@gmail.com
author: Nic Durish
description: "The slightly personal, slightly professional site of Nic Durish - Check out my portfolio, resume, or read some of my blogs!"
url: "https://nicdurish.ca"
timezone: Canada/Eastern

# Build settings
permalink: /:short_year-:month-:day/:title:output_ext
sass:
  sass_dir: css
  style: compressed

exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "README.md", "scss"]

# Social icons
show_social_icons: true
facebook_username: ndurish
linkedin_username: nicdurish
github_username: Durishn
instagram_username: nicdurish
twitter_username: durishn
couchsurfing_username: ndurish
spotify_username: durishn
youtube_username: NicDurish

# Google Analytics
google_analytics: UA-135084842-1

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"