# Site settings
title: Nic's Corner Of The Internet
email: mail@nicdurish.ca
author: Nic Durish
description: "Nic Durish is a web developer and designer based out of Guelph, Ontario. This site serves as his personal hub on the web. You'll find a bit of professional content, some pages where a stage my living documents and some occasional ramblings."
url: "https://nicdurish.ca"
timezone: Canada/Eastern

# Plugins
plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/blog/page:num/"

# Build settings
permalink: /:short_year-:month-:day/:title:output_ext
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "README.md", "scss"]
markdown_ext:   markdown,mkd,mkdn,md
sass:
  sass_dir: css
  style: compressed


# Social icons
show_social_icons: true
facebook_username: ndurish
linkedin_username: nicdurish
github_username: Durishn
instagram_username: nicdurish
twitter_username: durishn
couchsurfing_username: ndurish
spotify_username: durishn
youtube_username: NicDurish

# Google Analytics
google_analytics: UA-135084842-1

collections:
  projects:
    output: true
  presentations:
    output: true
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
