# Site settings
title: Nic's Corner Of The Internet
email: mail@nicdurish.ca
author: Nic Durish
description: "Nic Durish is a web developer and designer based out of Guelph, Ontario. This site serves as his personal hub on the web. You'll find a bit of professional content, some pages where a stage my living documents and some occasional ramblings."
url: "https://nicdurish.ca"
timezone: Canada/Eastern
language: "en"
lang_direction: "ltr"
color: "#152335"

# Plugins
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
# permalink: /:short_year-:month-:day/:title:output_ext
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "README.md", "scss"]
markdown_ext:   markdown,mkd,mkdn,md
sass:
  sass_dir: css
  style: compressed

availability_status: Open to new projects
availability_icon: fa-smile
availability_color: "96, 202, 155"

# Social icons
show_social_icons: true
# facebook_username: ndurish
linkedin_username: NicDurish
github_username: Durishn
# instagram_username: nicdurish
twitter_username: durishn
# couchsurfing_username: ndurish
# spotify_username: durishn
# youtube_username: NicDurish

our_services:
  - name: "Full-stack Web Development"
    image: "fas fa-code"
    description: "LAMP stacks, MERN stacks, and JAMstacks. Oh My! From the frontend, to the backend, to the database, and everything in-between."

  - name: 'Digital Product Design'
    image: 'fas fa-drafting-compass'
    description: "Clean, simple, and modern designs - optimized for responsiveness, performance, maintainability, and convertings users to customers."

  - name: 'Consultancy & Training'
    image: 'fas fa-chart-pie'
    description: 'Need some extra support to guide your development? I provide on or off-site consultations, training, and/or management on projects'

  - name: 'Analytics & Audits'
    image: 'fas fa-chart-pie'
    description: 'Get insights into your web product to improve performance, SEO, click-through and ultimately make smarter business decisions.'

  - name: 'Service Integration'
    image: 'fas fa-cogs'
    description: 'Get your product integrated with external services, APIs, Content Management Systems or databases. Or have some tailor-made!'

  - name: 'Accessibility & Usability'
    image: 'fas fa-universal-access'
    description: "Don't just be AODA or WCAG compliant - bring your product or service to new levels by prioritizing accessibility to all users across all platforms."


# Google Analytics
google_analytics: UA-135084842-1

collections:
  projects:
    output: true
  presentations:
    output: true
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
