---
label: Project
hide_body: true
fields:
- type: file
  name: banner
  label: banner
- type: text
  name: banneralttext
  label: banneralttext
- type: text
  name: title
  label: title
- type: textarea
  name: description
  label: description
- type: list
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
- type: list
  name: tags2
  label: tags2
- type: list
  name: atags
  label: atags
